name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  run-compile-crc:
    name: fedora-httpd
    uses: ./.github/workflows/reusable-action.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      actionfile: "fedora-httpd/README.md"
    secrets: inherit

  run-compile-macadam:
    name: debian-claude
    uses: ./.github/workflows/reusable-action.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      actionfile: "debian-claude/README.md"
    secrets: inherit

